// <auto-generated />
using System;
using DumpTether.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DumpTether.Data.Migrations
{
    [DbContext(typeof(DumpTetherDbContext))]
    [Migration("20260528202534_AddProjectSoftDelete")]
    partial class AddProjectSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DumpTether.Domain.ArchiveResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresExplanation")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_explanation");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("archive_resolutions", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.FieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TaskTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_template_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("TaskTemplateId", "Key");

                    b.HasIndex("TaskTemplateId", "SortOrder");

                    b.ToTable("field_definitions", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.FieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_definition_id");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_item_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("TaskItemId", "FieldDefinitionId")
                        .IsUnique();

                    b.ToTable("field_values", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name", "IsActive")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.SavedView", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("scope");

                    b.Property<string>("SortJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sort");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasFilter("project_id IS NULL AND deleted_at IS NULL");

                    b.HasIndex("WorkspaceId", "ProjectId", "Name")
                        .IsUnique()
                        .HasFilter("project_id IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("saved_views", null, t =>
                        {
                            t.HasCheckConstraint("ck_saved_views_scope_project", "(scope = 'Workspace' AND project_id IS NULL) OR (scope = 'Project' AND project_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DumpTether.Domain.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArchiveResolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("archive_resolution_id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Category")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FollowUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("follow_up_at");

                    b.Property<DateTimeOffset>("LastTouchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_touched_at");

                    b.Property<DateTimeOffset?>("LastViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_viewed_at");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaskTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveResolutionId");

                    b.HasIndex("FollowUpAt");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskTemplateId");

                    b.HasIndex("WorkspaceId", "Category");

                    b.HasIndex("WorkspaceId", "Color");

                    b.HasIndex("WorkspaceId", "ArchivedAt", "LastTouchedAt");

                    b.HasIndex("WorkspaceId", "ProjectId", "ArchivedAt");

                    b.ToTable("task_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_items_archive_requires_resolution", "(archived_at IS NULL AND archive_resolution_id IS NULL) OR (archived_at IS NOT NULL AND archive_resolution_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DumpTether.Domain.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name");

                    b.ToTable("task_templates", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.TaskTimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("details");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_item_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId", "OccurredAt");

                    b.ToTable("task_timeline_entries", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.ArchiveResolution", b =>
                {
                    b.HasOne("DumpTether.Domain.Workspace", null)
                        .WithMany("_archiveResolutions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.FieldDefinition", b =>
                {
                    b.HasOne("DumpTether.Domain.TaskTemplate", null)
                        .WithMany("_fieldDefinitions")
                        .HasForeignKey("TaskTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.FieldValue", b =>
                {
                    b.HasOne("DumpTether.Domain.FieldDefinition", null)
                        .WithMany()
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DumpTether.Domain.TaskItem", null)
                        .WithMany("_fieldValues")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.Project", b =>
                {
                    b.HasOne("DumpTether.Domain.Workspace", null)
                        .WithMany("_projects")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.SavedView", b =>
                {
                    b.HasOne("DumpTether.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DumpTether.Domain.Workspace", null)
                        .WithMany("_savedViews")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.TaskItem", b =>
                {
                    b.HasOne("DumpTether.Domain.ArchiveResolution", null)
                        .WithMany()
                        .HasForeignKey("ArchiveResolutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DumpTether.Domain.Project", null)
                        .WithMany("_taskItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DumpTether.Domain.TaskTemplate", null)
                        .WithMany()
                        .HasForeignKey("TaskTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DumpTether.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.TaskTemplate", b =>
                {
                    b.HasOne("DumpTether.Domain.Workspace", null)
                        .WithMany("_taskTemplates")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.TaskTimelineEntry", b =>
                {
                    b.HasOne("DumpTether.Domain.TaskItem", null)
                        .WithMany("_timelineEntries")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.Project", b =>
                {
                    b.Navigation("_taskItems");
                });

            modelBuilder.Entity("DumpTether.Domain.TaskItem", b =>
                {
                    b.Navigation("_fieldValues");

                    b.Navigation("_timelineEntries");
                });

            modelBuilder.Entity("DumpTether.Domain.TaskTemplate", b =>
                {
                    b.Navigation("_fieldDefinitions");
                });

            modelBuilder.Entity("DumpTether.Domain.Workspace", b =>
                {
                    b.Navigation("_archiveResolutions");

                    b.Navigation("_projects");

                    b.Navigation("_savedViews");

                    b.Navigation("_taskTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
