export type Language = 'en' | 'da';

const translations = {
  en: {
    account: 'Account',
    activeTask: 'Active task',
    addArchiveReason: 'Add archive reason',
    addNotePlaceholder: 'Add a note and press Enter...',
    addStatus: 'Add status',
    addTask: 'Add task',
    allProjects: 'All categories',
    allWorkspaces: 'All boards',
    anyCategory: 'Any category',
    anyColor: 'Any color',
    anyFollowUp: 'Any follow-up',
    anyProject: 'Any category',
    anyStatus: 'Any status',
    archive: 'Archive',
    archiveActions: 'Archive actions',
    archiveAction: 'Archive',
    archiveCategory: 'Archive category',
    archiveReasons: 'Archive reasons',
    archiveSelected: 'Archive selected',
    archiveTasks: 'Archive task(s)',
    archivedTask: 'Archived task',
    authLoggedIn: 'Signed in.',
    microsoftSignInFailed: 'Microsoft sign-in could not be completed. Please try again.',
    authRegistered: 'Account created and signed in.',
    authRequiredBody: 'Sign in or create a user before using this board.',
    authRequiredTitle: 'Sign in to DumpTether',
    authSettingsHelp: 'Local and hosted users use the same session and workspace rules.',
    backToWall: 'Back to wall',
    backendOffline: 'Backend connection is unavailable',
    backendOnline: 'Backend connection is healthy',
    board: 'Board',
    boardColor: 'Board color',
    cancel: 'Cancel',
    category: 'Category',
    changeCategory: 'Change category',
    changeColor: 'Change color',
    changeDueDate: 'Change due date',
    changeStatus: 'Change status',
    clearArchive: 'Clear archive',
    clearColor: 'Clear color',
    clearOldTasks: 'Clear old tasks...',
    clearTasksWithStatus: 'Clear archived tasks with status...',
    clearWorkspaceTasks: 'Clear board tasks...',
    cleanup: 'Cleanup',
    cleanupFuture: 'Permanent cleanup is limited to the selected board and always requires confirmation.',
    cleanupArchiveWarning: 'This permanently deletes matching archived tasks, including their notes and history. This cannot be undone.',
    cleanupCloudLinkedUnavailable: 'Permanent cleanup is paused for cloud-linked boards until deletions can sync safely.',
    cleanupBoard: 'Board to clean',
    cleanupNeedsOwnedBoard: 'Create or select an owned board before using permanent cleanup.',
    close: 'Close',
    collapseSidebar: 'Collapse sidebar',
    color: 'Color',
    confirmDelete: 'Sure?',
    connectionLostToast: 'Server connection was lost. You can keep looking at cached tasks, but changes may fail until it returns.',
    continueWith: 'Continue with',
    continueWithoutAccount: 'Continue without account',
    continueWithoutAccountHelp: 'Demo access does not save changes to the server. Sign up or login to save work.',
    copiedToClipboard: 'Copied to clipboard!',
    copySelected: 'Copy selected',
    copyToBoard: 'Copy to board',
    createBoardBeforeTasks: 'Create or select a board before creating tasks.',
    created: 'Created',
    currentSession: 'current',
    danish: 'Danish',
    declineInvite: 'Decline',
    deleteBoard: 'Delete board...',
    deleteBoardConfirmBody: 'This permanently deletes the board, tasks, archive, and history. It cannot be undone.',
    deleteBoardFuture: 'Board deletion needs a proper cleanup policy first.',
    deleteBoardNow: 'Delete board',
    deleteArchivedNow: 'Delete archived tasks',
    deleteArchivedTasksWarning: 'This permanently deletes the selected archived tasks, including notes, fields, shares, and history. It cannot be undone.',
    deleteCategoryNow: 'Delete category',
    deleteCategoryWarning: 'Delete this category and leave its tasks uncategorized?',
    deleteNote: 'Delete note',
    deletePermanently: 'Delete permanently',
    deleteProjectTag: 'Delete project tag...',
    developmentAccountHelp: 'Development only: creates or signs in as the local dev user.',
    deviceName: 'Device name',
    displayName: 'Display name',
    done: 'Stop selecting',
    draftTaskHelp: 'This draft is not saved yet. Add a title and create it, then notes and fields become available.',
    editBoard: 'Edit board',
    editMode: 'Edit mode',
    editProject: 'Edit category',
    editTask: 'Edit task',
    editView: 'Edit filter',
    email: 'Email',
    emailConfirmationSent: 'Confirmation email sent. Open it before logging in.',
    english: 'English',
    expires: 'Expires',
    expandSidebar: 'Expand sidebar',
    fieldsForFiltering: 'Fields',
    fieldsHelp: 'Structured fields make filtering possible without turning the wall into a form.',
    filterWall: 'Filter wall...',
    followUp: 'Follow-up',
    followUpDate: 'Follow-up date',
    guestModePersistent: 'Demo mode: sign up or login to save changes.',
    guestModeShort: 'Temporary',
    guestModeToast: 'Demo mode started. Sign up or login to save changes.',
    keep: 'Keep',
    language: 'Language',
    lastSeen: 'Last seen',
    lastPinged: 'Last pinged',
    lastUpdated: 'Last updated',
    lastVerified: 'Last verified',
    leaveBoard: 'Leave board',
    leaveCurrentBoard: 'Leave current board',
    leaveTaskShare: 'Leave shared task',
    localDesktopModePersistent: 'Running locally. Changes are saved on this device and are not synced to the cloud until you log in and choose what to sync.',
    localDesktopModeShort: 'Local',
    loadingAccount: 'Checking account...',
    loadingBoard: 'Loading board...',
    loadingTasks: 'Loading tasks...',
    login: 'Login',
    loginButton: 'Login',
    legalAcceptanceRequired: 'Review and accept the current Terms of Use and Privacy Notice to create an account.',
    legalAgreementJoin: 'and acknowledge the',
    legalAgreementPrefix: 'I agree to the',
    legalContactNotConfigured: 'Privacy contact not configured',
    legalInformation: 'Legal information',
    legalOperatorNotConfigured: 'Service operator not configured',
    legalVersion: 'Version',
    logout: 'Logout',
    liveUpdatesDisconnected: 'Live updates disconnected. Refresh still works.',
    manageBoards: 'Manage boards',
    newProjectTag: 'New category',
    newTask: 'New task',
    newTaskPlaceholder: 'Add a task and press Enter...',
    newTaskTitlePlaceholder: 'Task title...',
    newView: 'Save filter',
    newWorkspace: 'New board',
    noCategory: 'No category',
    noCategoriesYet: 'No categories yet',
    noColor: 'No color',
    noFollowUp: 'No follow-up',
    noBoardSelected: 'Create a board first, then add tasks to it.',
    noNotesYet: 'No notes yet',
    noStatus: 'No status',
    noTaskColors: 'No task colors yet',
    or: 'or',
    noArchivedTasksToDelete: 'No matching archived tasks were found.',
    noTasks: 'Nothing here yet. Use + to add your first task.',
    noTasksMatch: 'No tasks match these filters. Reset filters to see the whole wall again.',
    noIncomingNotifications: 'No pending invitations or shared tasks.',
    noSessions: 'No sessions yet.',
    notSignedIn: 'Not signed in',
    notTouchedDays: 'Not touched days',
    olderThanDays: 'Older than days',
    note: 'Note',
    noteCount: 'notes',
    notes: 'Notes',
    offline: 'Offline',
    online: 'Online',
    overview: 'All tasks',
    password: 'Password',
    passwordRequirement: 'Use at least 8 characters. Longer passphrases are better.',
    privacyControllerTitle: 'Controller and contact',
    privacyCookiesBody: 'DumpTether uses strictly necessary session and security cookies. No advertising or analytics cookies are used by the current service.',
    privacyCookiesTitle: 'Cookies',
    privacyDataBody: 'We process account details, session and security metadata, and the boards, tasks, notes, fields, sharing records, and settings you choose to store.',
    privacyDataTitle: 'Data we process',
    privacyNotice: 'Privacy Notice',
    privacyProvidersBody: 'Infrastructure and delivery providers may process data on our behalf, including the hosting provider, Cloudflare, Brevo, and Microsoft when you choose Microsoft sign-in. Provider agreements and international transfer safeguards must be maintained operationally.',
    privacyProvidersTitle: 'Service providers',
    privacyPurposeBody: 'We process data to provide and secure DumpTether, fulfil the service contract, prevent abuse, and meet legal obligations. We do not sell personal data.',
    privacyPurposeTitle: 'Purposes and legal bases',
    privacyRetentionBody: 'Content is kept while your account or workspace needs it. Sessions and archived items follow configured retention periods. Backups and operational logs may have separate limited retention. Account deletion and portable export are being completed before broad public availability.',
    privacyRetentionTitle: 'Retention',
    privacyRightsBody: 'Depending on the circumstances, you may request access, correction, deletion, restriction, objection, or portability, and you may complain to the Danish Data Protection Agency. Contact the privacy address shown above.',
    privacyRightsTitle: 'Your rights',
    projectTags: 'Categories',
    refresh: 'Refresh',
    register: 'Register',
    registerButton: 'Create account',
    registerWith: 'Sign up with',
    removeMember: 'Remove member',
    removeFilters: 'Remove filters',
    requireArchiveNote: 'Require archive note',
    resetFilters: 'Reset filters',
    revoked: 'Revoked',
    revokeSession: 'Revoke',
    roleMember: 'Member',
    roleOwner: 'Owner',
    roleReadOnly: 'Read-only / Guest',
    save: 'Save',
    saveFailed: 'Save failed',
    saveFields: 'Save fields',
    saved: 'Saved',
    savedViews: 'Wall',
    saving: 'Saving...',
    sessionBrowser: 'Browser',
    sessionDesktopCloud: 'Desktop cloud',
    sessionDesktopLocal: 'Local desktop',
    sessionDevelopment: 'Development',
    sessionGuest: 'Guest',
    sessionRevoked: 'Session revoked.',
    sessions: 'Sessions',
    selectTasksForAction: 'Select task(s) for action',
    selectedTasks: 'selected',
    settings: 'Settings',
    settingsGeneral: 'General',
    settingsSections: 'Settings sections',
    signedInAs: 'Signed in as',
    signupClosed: 'Registration is closed on this server. Ask the owner for access.',
    signupInviteOnlyHelp: 'This server is invite-only. Enter your invite code to create an account.',
    signupWhitelistHelp: 'This server only accepts approved emails or domains.',
    sortAscending: 'ascending',
    sortCreated: 'Created',
    sortDescending: 'descending',
    sortFollowUp: 'Follow-up',
    sortLastTouched: 'Last updated',
    sortStatus: 'Status',
    sortTitle: 'Title',
    sortedBy: 'Sorted by',
    stale: 'Stale',
    status: 'Status',
    statusOptions: 'Status options',
    taskColor: 'Task color',
    taskFields: 'Task fields',
    taskTitleRequired: 'Title *',
    templateImported: 'Template imported.',
    termsAcceptableUseBody: 'Do not misuse the service, attempt unauthorized access, interfere with other users, or upload unlawful content. You are responsible for activity under your account.',
    termsAcceptableUseTitle: 'Acceptable use',
    termsAvailabilityBody: 'DumpTether is evolving and may change, pause, or end. Availability, uninterrupted operation, and permanent preservation of data are not guaranteed. Keep independent backups of important information.',
    termsAvailabilityTitle: 'Availability and changes',
    termsChangesBody: 'Material changes will use a new document version and may require acceptance before further account use. Statutory consumer and data-protection rights are unaffected.',
    termsChangesTitle: 'Changes to these terms',
    termsContentBody: 'You retain ownership of your content and give the service permission to process it only as needed to operate, secure, share, synchronize, and back up DumpTether according to your choices.',
    termsContentTitle: 'Your content',
    termsLiabilityBody: 'The service is provided without promises beyond those required by law. To the extent permitted by law, the operator is not liable for indirect loss or loss caused by use outside the intended service. Mandatory rights remain in force.',
    termsLiabilityTitle: 'Responsibility',
    termsOfUse: 'Terms of Use',
    termsServiceBody: 'These terms govern use of the hosted DumpTether service. You must provide accurate account information, protect your sign-in methods, and use the service lawfully.',
    termsServiceTitle: 'The service',
    templates: 'Task templates',
    undo: 'Undo',
    unarchiveNote: 'Unarchive note (optional)',
    unarchiveSelected: 'Unarchive selected',
    unknownDevice: 'Unknown device',
    updatingTasks: 'Updating...',
    useDevelopmentAccount: 'Use dev account',
    waiting: 'Waiting',
    wallHelp: 'Search tasks by text, category, status, field values, color, and dates.',
    acceptInvite: 'Accept invite',
    inviteEmail: 'Invite email',
    inviteCode: 'Invite code',
    inviteMember: 'Invite member',
    inviteToken: 'Invite token',
    inviteTokenHelp: 'Copy this token to the other user while email delivery is paused.',
    inviteUrl: 'Invite URL',
    importTemplate: 'Import template',
    importTemplateHelp: 'Copy this task structure into your template library.',
    members: 'Members',
    notShared: 'Not shared',
    pendingInvites: 'pending',
    removeShare: 'Remove share',
    revokeInvite: 'Revoke invite',
    shareEmail: 'Share email',
    shareRole: 'Share role',
    shareLinkHelp: 'Copy this one-time link to the invited user. It expires after one day unless revoked first.',
    shareSelected: 'Share selected',
    shareTask: 'Share task',
    sharedWith: 'Shared with',
    sharedWithMe: 'Shared with me',
    sharedBy: 'Shared by',
    sharedWorkspace: 'Shared board',
    boardAccessCannotCreateTasks: 'This board access cannot create new tasks.',
    sharedBoardsCannotCreateTasks: 'This board access cannot create new tasks.',
    sharing: 'Sharing',
    invitedBy: 'Invited by',
    notifications: 'Notifications',
    taskShareLeft: 'Shared task left.',
    tasksCopied: 'Task(s) copied.',
    tasksDeletedPermanently: 'Archived task(s) deleted.',
    tasksUnarchived: 'Task(s) unarchived.',
    workspaceColor: 'Board color',
    workspaceInviteAccepted: 'Invitation accepted.',
    workspaceInviteDeclined: 'Invitation declined.',
    workspaceDeleted: 'Board deleted.',
    systemBoardCannotBeDeleted: 'All tasks is a standard wall and cannot be deleted.',
    cloudAccount: 'Cloud account',
    cloudAccountConnected: 'Cloud account connected.',
    cloudAccountDisconnected: 'Cloud account disconnected.',
    cloudAccountHelp: 'Connect this local desktop to the cloud server configured for this client.',
    cloudAccountRequiredForSync: 'Connect a cloud account in Account before syncing this board.',
    cloudSyncPaused: 'Cloud sync is paused; local work is still safe',
    cloudApiUrl: 'Cloud API URL',
    cloudServerUrl: 'Cloud server URL',
    cloudServerUrlNotConfigured: 'No cloud server URL is configured for this client.',
    cloudSessionToken: 'Cloud session token',
    cloudSync: 'Cloud sync',
    connectCloudAccount: 'Login',
    disconnectCloudAccount: 'Disconnect cloud account',
    pullCloudChanges: 'Pull cloud changes',
    pushLocalChanges: 'Push local changes',
    retrySync: 'Retry sync',
    syncBoard: 'Sync board',
    syncComplete: 'Sync complete',
    syncConflicts: 'Conflicts',
    syncConflict: 'Sync conflict',
    syncDeleted: 'Deleted in sync',
    syncError: 'Sync error',
    syncFailed: 'Sync failed',
    syncFailedCount: 'Failed',
    syncLastAttempt: 'Last sync attempt',
    syncLastSynced: 'Last synced',
    syncMessages: 'Sync messages',
    syncNeedsReview: 'Needs review',
    syncNow: 'Sync now',
    syncPushed: 'Pushed',
    syncPulled: 'Pulled',
    syncRecoveryHelp: 'Conflicts and failed items are kept on both sides. Open the task, decide what should win, then retry sync.',
    syncRootAccessRevoked: 'Cloud access removed',
    syncRootLinked: 'Linked',
    syncRootLocalOnly: 'Local only',
    syncStats: 'Sync stats',
    syncSynced: 'Up to date',
    syncing: 'Syncing...',
    syncTokenHelp: 'Paste a browser/cloud session token for this run. DumpTether remembers only the cloud URL, not the token.',
    syncUnknown: 'Sync state unknown',
    syncUpdatedLocal: 'Updated local',
    syncUpdatedRemote: 'Updated cloud',
    workspaceInvites: 'Board invitations',
    workspaceLeft: 'Board left.',
    workspaces: 'Boards',
  },
  da: {
    account: 'Konto',
    activeTask: 'Aktiv opgave',
    addArchiveReason: 'Tilføj arkivårsag',
    addNotePlaceholder: 'Tilføj en note og tryk Enter...',
    addStatus: 'Tilføj status',
    addTask: 'Tilføj opgave',
    allProjects: 'Alle kategorier',
    allWorkspaces: 'Alle tavler',
    anyCategory: 'Alle kategorier',
    anyColor: 'Alle farver',
    anyFollowUp: 'Alle opfølgninger',
    anyProject: 'Alle kategorier',
    anyStatus: 'Alle statusser',
    archive: 'Arkiv',
    archiveActions: 'Arkivhandlinger',
    archiveAction: 'Arkivér',
    archiveCategory: 'Arkivér kategori',
    archiveReasons: 'Arkivårsager',
    archiveSelected: 'Arkivér valgte',
    archiveTasks: 'Arkivér opgave(r)',
    archivedTask: 'Arkiveret opgave',
    authLoggedIn: 'Logget ind.',
    microsoftSignInFailed: 'Microsoft-login kunne ikke gennemføres. Prøv igen.',
    authRegistered: 'Konto oprettet og logget ind.',
    authRequiredBody: 'Log ind eller opret en bruger, før du bruger tavlen.',
    authRequiredTitle: 'Log ind på DumpTether',
    authSettingsHelp: 'Lokale og hostede brugere bruger samme session- og tavleregler.',
    backToWall: 'Tilbage til tavlen',
    backendOffline: 'Backendforbindelsen er ikke tilgængelig',
    backendOnline: 'Backendforbindelsen virker',
    board: 'Tavle',
    boardColor: 'Tavlefarve',
    cancel: 'Annuller',
    category: 'Kategori',
    changeCategory: 'Skift kategori',
    changeColor: 'Skift farve',
    changeDueDate: 'Skift dato',
    changeStatus: 'Skift status',
    clearArchive: 'Ryd arkiv',
    clearColor: 'Ryd farve',
    clearOldTasks: 'Ryd gamle opgaver...',
    clearTasksWithStatus: 'Ryd arkiverede opgaver med status...',
    clearWorkspaceTasks: 'Ryd opgaver i tavle...',
    cleanup: 'Oprydning',
    cleanupFuture: 'Permanent oprydning er begrænset til den valgte tavle og kræver altid bekræftelse.',
    cleanupArchiveWarning: 'Dette sletter matchende arkiverede opgaver permanent, inklusive noter og historik. Det kan ikke fortrydes.',
    cleanupCloudLinkedUnavailable: 'Permanent oprydning er sat på pause for cloud-forbundne tavler, indtil sletninger kan synkroniseres sikkert.',
    cleanupBoard: 'Tavle der skal ryddes op',
    cleanupNeedsOwnedBoard: 'Opret eller vælg en tavle, du ejer, før permanent oprydning kan bruges.',
    close: 'Luk',
    collapseSidebar: 'Skjul sidebar',
    color: 'Farve',
    confirmDelete: 'Sikker?',
    connectionLostToast: 'Forbindelsen til serveren er væk. Du kan se cachede opgaver, men ændringer kan fejle indtil den er tilbage.',
    continueWith: 'Fortsæt med',
    continueWithoutAccount: 'Fortsæt uden konto',
    continueWithoutAccountHelp: 'Demo-adgang gemmer ikke aendringer paa serveren. Opret konto eller log ind for at gemme.',
    copiedToClipboard: 'Kopieret til udklipsholder!',
    copySelected: 'Kopier valgte',
    copyToBoard: 'Kopier til tavle',
    createBoardBeforeTasks: 'Opret eller vælg en tavle, før du opretter opgaver.',
    created: 'Oprettet',
    currentSession: 'aktuel',
    danish: 'Dansk',
    declineInvite: 'Afvis',
    deleteBoard: 'Slet tavle...',
    deleteBoardConfirmBody: 'Dette sletter tavlen, opgaver, arkiv og historik permanent. Handlingen kan ikke fortrydes.',
    deleteBoardFuture: 'Slet tavle er planlagt og kræver en rigtig ryddepolitik først.',
    deleteBoardNow: 'Slet tavle',
    deleteArchivedNow: 'Slet arkiverede opgaver',
    deleteArchivedTasksWarning: 'Dette sletter de valgte arkiverede opgaver permanent, inklusive noter, felter, delinger og historik. Handlingen kan ikke fortrydes.',
    deleteCategoryNow: 'Slet kategori',
    deleteCategoryWarning: 'Slet denne kategori og lad opgaverne stå uden kategori?',
    deleteNote: 'Slet note',
    deletePermanently: 'Slet permanent',
    deleteProjectTag: 'Slet kategori...',
    developmentAccountHelp: 'Kun udvikling: opretter eller logger ind som lokal dev-bruger.',
    deviceName: 'Enhedsnavn',
    displayName: 'Visningsnavn',
    done: 'Stop valg',
    draftTaskHelp: 'Denne kladde er ikke gemt endnu. Skriv en titel og opret den, så kan du tilføje noter og felter bagefter.',
    editBoard: 'Rediger tavle',
    editMode: 'Rediger',
    editProject: 'Rediger kategori',
    editTask: 'Rediger opgave',
    editView: 'Rediger filter',
    email: 'Email',
    emailConfirmationSent: 'Bekræftelsesmail sendt. Åbn den før login.',
    english: 'Engelsk',
    expires: 'Udløber',
    expandSidebar: 'Vis sidebar',
    fieldsForFiltering: 'Felter',
    fieldsHelp: 'Strukturerede felter gør det muligt at filtrere uden at gøre tavlen til en stor formular.',
    filterWall: 'Filtrer tavlen...',
    followUp: 'Opfølgning',
    followUpDate: 'Opfølgning',
    guestModePersistent: 'Demo-tilstand: opret konto eller log ind for at gemme aendringer.',
    guestModeShort: 'Midlertidig',
    guestModeToast: 'Demo-tilstand startet. Opret konto eller log ind for at gemme.',
    keep: 'Behold',
    language: 'Sprog',
    lastSeen: 'Sidst set',
    lastPinged: 'Sidst pinget',
    lastUpdated: 'Sidst opdateret',
    lastVerified: 'Sidst bekræftet',
    leaveBoard: 'Forlad tavle',
    leaveCurrentBoard: 'Forlad aktuel tavle',
    leaveTaskShare: 'Forlad delt opgave',
    localDesktopModePersistent: 'Kører lokalt. Ændringer gemmes på denne enhed og synkroniseres ikke til cloud, før du logger ind og vælger hvad der skal synkroniseres.',
    localDesktopModeShort: 'Lokal',
    loadingAccount: 'Tjekker konto...',
    loadingBoard: 'Indlæser tavle...',
    loadingTasks: 'Indlæser opgaver...',
    login: 'Log ind',
    loginButton: 'Log ind',
    legalAcceptanceRequired: 'Læs og acceptér de gældende brugsbetingelser og privatlivsmeddelelsen for at oprette en konto.',
    legalAgreementJoin: 'og har læst',
    legalAgreementPrefix: 'Jeg accepterer',
    legalContactNotConfigured: 'Kontakt til privatliv er ikke konfigureret',
    legalInformation: 'Juridisk information',
    legalOperatorNotConfigured: 'Tjenestens operatør er ikke konfigureret',
    legalVersion: 'Version',
    logout: 'Log ud',
    liveUpdatesDisconnected: 'Live opdateringer er afbrudt. Opdater virker stadig.',
    manageBoards: 'Administrer tavler',
    newProjectTag: 'Ny kategori',
    newTask: 'Ny opgave',
    newTaskPlaceholder: 'Tilføj en opgave og tryk Enter...',
    newTaskTitlePlaceholder: 'Opgavetitel...',
    newView: 'Gem filter',
    newWorkspace: 'Ny tavle',
    noCategory: 'Ingen kategori',
    noCategoriesYet: 'Ingen kategorier endnu',
    noColor: 'Ingen farve',
    noFollowUp: 'Ingen opfølgning',
    noBoardSelected: 'Opret en tavle først, og tilføj derefter opgaver.',
    noNotesYet: 'Ingen noter endnu',
    noStatus: 'Ingen status',
    noTaskColors: 'Ingen opgavefarver endnu',
    or: 'eller',
    noArchivedTasksToDelete: 'Der blev ikke fundet matchende arkiverede opgaver.',
    noTasks: 'Her er tomt endnu. Brug + for at tilføje din første opgave.',
    noTasksMatch: 'Ingen opgaver matcher filtrene. Nulstil filtrene for at se hele tavlen igen.',
    noIncomingNotifications: 'Ingen ventende invitationer eller delte opgaver.',
    noSessions: 'Ingen sessioner endnu.',
    notSignedIn: 'Ikke logget ind',
    notTouchedDays: 'Ikke rørt i dage',
    olderThanDays: 'Ældre end antal dage',
    note: 'Note',
    noteCount: 'noter',
    notes: 'Noter',
    offline: 'Offline',
    online: 'Online',
    overview: 'Alle opgaver',
    password: 'Adgangskode',
    passwordRequirement: 'Brug mindst 8 tegn. En længere adgangssætning er bedre.',
    privacyControllerTitle: 'Dataansvarlig og kontakt',
    privacyCookiesBody: 'DumpTether bruger kun nødvendige sessions- og sikkerhedscookies. Den nuværende tjeneste bruger ikke reklame- eller analysecookies.',
    privacyCookiesTitle: 'Cookies',
    privacyDataBody: 'Vi behandler kontooplysninger, sessions- og sikkerhedsmetadata samt de tavler, opgaver, noter, felter, delinger og indstillinger, du vælger at gemme.',
    privacyDataTitle: 'Oplysninger vi behandler',
    privacyNotice: 'Privatlivsmeddelelse',
    privacyProvidersBody: 'Leverandører kan behandle oplysninger på vores vegne, herunder hostingudbyderen, Cloudflare, Brevo og Microsoft, når du vælger Microsoft-login. Databehandleraftaler og grundlag for internationale overførsler skal vedligeholdes driftsmæssigt.',
    privacyProvidersTitle: 'Leverandører',
    privacyPurposeBody: 'Vi behandler oplysninger for at levere og sikre DumpTether, opfylde aftalen, forebygge misbrug og overholde lovkrav. Vi sælger ikke personoplysninger.',
    privacyPurposeTitle: 'Formål og behandlingsgrundlag',
    privacyRetentionBody: 'Indhold opbevares, mens din konto eller tavle har brug for det. Sessioner og arkiverede elementer følger de konfigurerede slettefrister. Sikkerhedskopier og driftslogs kan have særskilte, begrænsede frister. Kontosletning og portabel eksport færdiggøres før bred offentlig adgang.',
    privacyRetentionTitle: 'Opbevaring',
    privacyRightsBody: 'Afhængigt af omstændighederne kan du anmode om indsigt, rettelse, sletning, begrænsning, indsigelse eller dataportabilitet, og du kan klage til Datatilsynet. Kontakt privatlivsadressen ovenfor.',
    privacyRightsTitle: 'Dine rettigheder',
    projectTags: 'Kategorier',
    refresh: 'Opdater',
    register: 'Opret konto',
    registerButton: 'Opret konto',
    registerWith: 'Opret med',
    removeMember: 'Fjern medlem',
    removeFilters: 'Fjern filtre',
    requireArchiveNote: 'Kræv arkivnote',
    resetFilters: 'Nulstil filtre',
    revoked: 'Tilbagekaldt',
    revokeSession: 'Tilbagekald',
    roleMember: 'Medlem',
    roleOwner: 'Ejer',
    roleReadOnly: 'Læseadgang / gæst',
    save: 'Gem',
    saveFailed: 'Kunne ikke gemme',
    saveFields: 'Gem felter',
    saved: 'Gemt',
    savedViews: 'Tavle',
    saving: 'Gemmer...',
    sessionBrowser: 'Browser',
    sessionDesktopCloud: 'Desktop cloud',
    sessionDesktopLocal: 'Lokal desktop',
    sessionDevelopment: 'Udvikling',
    sessionGuest: 'Gæst',
    sessionRevoked: 'Session tilbagekaldt.',
    sessions: 'Sessioner',
    selectTasksForAction: 'Vælg opgave(r) til handling',
    selectedTasks: 'valgt',
    settings: 'Indstillinger',
    settingsGeneral: 'Generelt',
    settingsSections: 'Indstillingsområder',
    signedInAs: 'Logget ind som',
    signupClosed: 'Oprettelse er lukket paa denne server. Spoerg ejeren om adgang.',
    signupInviteOnlyHelp: 'Denne server kraever invitation. Indtast din invitationskode for at oprette konto.',
    signupWhitelistHelp: 'Denne server tillader kun godkendte emails eller domainer.',
    sortAscending: 'stigende',
    sortCreated: 'Oprettet',
    sortDescending: 'faldende',
    sortFollowUp: 'Opfølgning',
    sortLastTouched: 'Sidst opdateret',
    sortStatus: 'Status',
    sortTitle: 'Titel',
    sortedBy: 'Sorteret efter',
    stale: 'Gammel',
    status: 'Status',
    statusOptions: 'Statusmuligheder',
    taskColor: 'Opgavefarve',
    taskFields: 'Opgavefelter',
    taskTitleRequired: 'Titel *',
    templateImported: 'Skabelon importeret.',
    termsAcceptableUseBody: 'Du må ikke misbruge tjenesten, forsøge uautoriseret adgang, forstyrre andre brugere eller gemme ulovligt indhold. Du er ansvarlig for aktivitet på din konto.',
    termsAcceptableUseTitle: 'Tilladt brug',
    termsAvailabilityBody: 'DumpTether er under udvikling og kan ændres, sættes på pause eller ophøre. Oppetid, uafbrudt drift og permanent bevaring af data garanteres ikke. Bevar selvstændige sikkerhedskopier af vigtige oplysninger.',
    termsAvailabilityTitle: 'Drift og ændringer',
    termsChangesBody: 'Væsentlige ændringer får en ny dokumentversion og kan kræve accept før videre brug. Ufravigelige forbruger- og databeskyttelsesrettigheder påvirkes ikke.',
    termsChangesTitle: 'Ændringer til betingelserne',
    termsContentBody: 'Du beholder ejerskabet til dit indhold og giver kun tjenesten tilladelse til at behandle det, når det er nødvendigt for at drive, sikre, dele, synkronisere og sikkerhedskopiere DumpTether efter dine valg.',
    termsContentTitle: 'Dit indhold',
    termsLiabilityBody: 'Tjenesten leveres uden løfter ud over dem, loven kræver. I det omfang loven tillader det, er operatøren ikke ansvarlig for indirekte tab eller tab ved brug uden for tjenestens formål. Ufravigelige rettigheder gælder fortsat.',
    termsLiabilityTitle: 'Ansvar',
    termsOfUse: 'Brugsbetingelser',
    termsServiceBody: 'Disse betingelser gælder for brug af den hostede DumpTether-tjeneste. Du skal give korrekte kontooplysninger, beskytte dine loginmetoder og bruge tjenesten lovligt.',
    termsServiceTitle: 'Tjenesten',
    templates: 'Opgaveskabeloner',
    undo: 'Fortryd',
    unarchiveNote: 'Genåbningsnote (valgfri)',
    unarchiveSelected: 'Genåbn valgte',
    updatingTasks: 'Opdaterer...',
    unknownDevice: 'Ukendt enhed',
    useDevelopmentAccount: 'Brug dev-konto',
    waiting: 'Afventer',
    wallHelp: 'Søg i opgaver efter tekst, kategori, status, feltværdier, farve og datoer.',
    acceptInvite: 'Accepter invitation',
    inviteEmail: 'Inviter email',
    inviteCode: 'Invitationskode',
    inviteMember: 'Inviter medlem',
    inviteToken: 'Invitationstoken',
    inviteTokenHelp: 'Kopier denne token til den anden bruger mens email er sat paa pause.',
    inviteUrl: 'Invitationslink',
    importTemplate: 'Importer skabelon',
    importTemplateHelp: 'Kopier denne opgaves struktur til dine skabeloner.',
    members: 'Medlemmer',
    notShared: 'Ikke delt',
    pendingInvites: 'afventer',
    removeShare: 'Fjern deling',
    revokeInvite: 'Tilbagekald invitation',
    shareEmail: 'Delings-email',
    shareRole: 'Delingsrolle',
    shareLinkHelp: 'Kopier dette engangslink til den inviterede bruger. Det udløber efter én dag, medmindre det tilbagekaldes først.',
    shareSelected: 'Del valgte',
    shareTask: 'Del opgave',
    sharedWith: 'Delt med',
    sharedWithMe: 'Delt med mig',
    sharedBy: 'Delt af',
    sharedWorkspace: 'Delt tavle',
    boardAccessCannotCreateTasks: 'Denne tavleadgang kan ikke oprette nye opgaver.',
    sharedBoardsCannotCreateTasks: 'Denne tavleadgang kan ikke oprette nye opgaver.',
    sharing: 'Deling',
    invitedBy: 'Inviteret af',
    notifications: 'Notifikationer',
    taskShareLeft: 'Delt opgave forladt.',
    tasksCopied: 'Opgave(r) kopieret.',
    tasksDeletedPermanently: 'Arkiverede opgave(r) slettet.',
    tasksUnarchived: 'Opgave(r) genåbnet.',
    workspaceColor: 'Tavlefarve',
    workspaceInviteAccepted: 'Invitation accepteret.',
    workspaceInviteDeclined: 'Invitation afvist.',
    workspaceDeleted: 'Tavlen blev slettet.',
    systemBoardCannotBeDeleted: 'Alle opgaver er en standardtavle og kan ikke slettes.',
    cloudAccount: 'Cloud-konto',
    cloudAccountConnected: 'Cloud-konto forbundet.',
    cloudAccountDisconnected: 'Cloud-konto afbrudt.',
    cloudAccountHelp: 'Forbind denne lokale desktop til cloud-serveren, der er konfigureret for denne klient.',
    cloudAccountRequiredForSync: 'Forbind en cloud-konto under Konto, før du synker denne tavle.',
    cloudSyncPaused: 'Cloud-synkronisering er sat på pause; lokalt arbejde er stadig sikkert',
    cloudApiUrl: 'Cloud API-URL',
    cloudServerUrl: 'Cloud-server URL',
    cloudServerUrlNotConfigured: 'Der er ikke konfigureret en cloud-server URL for denne klient.',
    cloudSessionToken: 'Cloud-sessiontoken',
    cloudSync: 'Cloud-synk',
    connectCloudAccount: 'Log ind',
    disconnectCloudAccount: 'Afbryd cloud-konto',
    pullCloudChanges: 'Hent cloud-ændringer',
    pushLocalChanges: 'Send lokale ændringer',
    retrySync: 'Prøv synk igen',
    syncBoard: 'Synk tavle',
    syncComplete: 'Synk færdig',
    syncConflicts: 'Konflikter',
    syncConflict: 'Synkkonflikt',
    syncDeleted: 'Slettet i synk',
    syncError: 'Synkfejl',
    syncFailed: 'Synk fejlede',
    syncFailedCount: 'Fejlede',
    syncLastAttempt: 'Sidste synkforsøg',
    syncLastSynced: 'Sidst synket',
    syncMessages: 'Synkbeskeder',
    syncNeedsReview: 'Kræver gennemgang',
    syncNow: 'Synk nu',
    syncPushed: 'Sendt',
    syncPulled: 'Hentet',
    syncRecoveryHelp: 'Konflikter og fejlede elementer beholdes på begge sider. Åbn opgaven, vælg hvad der skal gælde, og prøv synk igen.',
    syncRootAccessRevoked: 'Cloud-adgang fjernet',
    syncRootLinked: 'Forbundet',
    syncRootLocalOnly: 'Kun lokalt',
    syncStats: 'Synkstatus',
    syncSynced: 'Opdateret',
    syncing: 'Synker...',
    syncTokenHelp: 'Indsæt et browser/cloud-sessiontoken for denne kørsel. DumpTether husker kun cloud-URLen, ikke tokenet.',
    syncUnknown: 'Ukendt synkstatus',
    syncUpdatedLocal: 'Opdateret lokalt',
    syncUpdatedRemote: 'Opdateret i cloud',
    workspaceInvites: 'Tavleinvitationer',
    workspaceLeft: 'Tavle forladt.',
    workspaces: 'Tavler',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;
export type Translate = (key: TranslationKey) => string;

export function translate(language: Language, key: TranslationKey) {
  return translations[language][key] ?? translations.en[key];
}
