export type Language = 'en' | 'da';

const translations = {
  en: {
    account: 'Account',
    activeTask: 'Active task',
    addArchiveReason: 'Add archive reason',
    addNotePlaceholder: 'Add a note and press Enter...',
    addStatus: 'Add status',
    addTask: 'Add task',
    allProjects: 'All categories',
    allWorkspaces: 'All boards',
    anyCategory: 'Any category',
    anyColor: 'Any color',
    anyFollowUp: 'Any follow-up',
    anyProject: 'Any category',
    anyStatus: 'Any status',
    archive: 'Archive',
    archiveActions: 'Archive actions',
    archiveAction: 'Archive',
    archiveCategory: 'Archive category',
    archiveReasons: 'Archive reasons',
    archiveSelected: 'Archive selected',
    archiveTasks: 'Archive task(s)',
    archivedTask: 'Archived task',
    authLoggedIn: 'Signed in.',
    authRegistered: 'Account created and signed in.',
    authRequiredBody: 'Sign in or create a user before using this board.',
    authRequiredTitle: 'Sign in to DumpTether',
    authSettingsHelp: 'Local and hosted users use the same session and workspace rules.',
    backToWall: 'Back to wall',
    backendOffline: 'Backend connection is unavailable',
    backendOnline: 'Backend connection is healthy',
    board: 'Board',
    boardColor: 'Board color',
    cancel: 'Cancel',
    category: 'Category',
    changeCategory: 'Change category',
    changeColor: 'Change color',
    changeDueDate: 'Change due date',
    changeStatus: 'Change status',
    clearArchive: 'Clear archive',
    clearColor: 'Clear color',
    clearOldTasks: 'Clear old tasks...',
    clearWorkspaceTasks: 'Clear board tasks...',
    cleanup: 'Cleanup',
    cleanupFuture: 'Permanent cleanup is limited to the selected board and always requires confirmation.',
    cleanupArchiveWarning: 'This permanently deletes matching archived tasks, including their notes and history. This cannot be undone.',
    cleanupCloudLinkedUnavailable: 'Permanent cleanup is paused for cloud-linked boards until deletions can sync safely.',
    cleanupBoard: 'Board to clean',
    cleanupNeedsOwnedBoard: 'Create or select an owned board before using permanent cleanup.',
    close: 'Close',
    collapseSidebar: 'Collapse sidebar',
    color: 'Color',
    configRequired: 'Config needed',
    confirmDelete: 'Sure?',
    connectionLostToast: 'Server connection was lost. You can keep looking at cached tasks, but changes may fail until it returns.',
    continueWith: 'Continue with',
    continueWithoutAccount: 'Continue without account',
    continueWithoutAccountHelp: 'Demo access does not save changes to the server. Sign up or login to save work.',
    copiedToClipboard: 'Copied to clipboard!',
    copySelected: 'Copy selected',
    copyToBoard: 'Copy to board',
    createBoardBeforeTasks: 'Create or select a board before creating tasks.',
    created: 'Created',
    currentSession: 'current',
    danish: 'Danish',
    declineInvite: 'Decline',
    deleteBoard: 'Delete board...',
    deleteBoardConfirmBody: 'This permanently deletes the board, tasks, archive, and history. It cannot be undone.',
    deleteBoardFuture: 'Board deletion needs a proper cleanup policy first.',
    deleteBoardNow: 'Delete board',
    deleteArchivedNow: 'Delete archived tasks',
    deleteArchivedTasksWarning: 'This permanently deletes the selected archived tasks, including notes, fields, shares, and history. It cannot be undone.',
    deleteCategoryNow: 'Delete category',
    deleteCategoryWarning: 'Delete this category and leave its tasks uncategorized?',
    deleteNote: 'Delete note',
    deletePermanently: 'Delete permanently',
    deleteProjectTag: 'Delete project tag...',
    developmentAccountHelp: 'Development only: creates or signs in as the local dev user.',
    deviceName: 'Device name',
    displayName: 'Display name',
    done: 'Stop selecting',
    draftTaskHelp: 'This draft is not saved yet. Add a title and create it, then notes and fields become available.',
    editBoard: 'Edit board',
    editMode: 'Edit mode',
    editProject: 'Edit category',
    editTask: 'Edit task',
    editView: 'Edit filter',
    email: 'Email',
    emailConfirmationSent: 'Confirmation email sent. Open it before logging in.',
    emailMfa: 'Email MFA',
    emailMfaHelp: 'Future suspicious-login checks will send a short code by email.',
    emailPasswordLogin: 'Email and password',
    emailPasswordLoginHelp: 'Available now. Email confirmation is the next hardening step.',
    english: 'English',
    expires: 'Expires',
    expandSidebar: 'Expand sidebar',
    fieldsForFiltering: 'Fields',
    fieldsHelp: 'Structured fields make filtering possible without turning the wall into a form.',
    filterWall: 'Filter wall...',
    followUp: 'Follow-up',
    followUpDate: 'Follow-up date',
    guestModePersistent: 'Demo mode: sign up or login to save changes.',
    guestModeShort: 'Temporary',
    guestModeToast: 'Demo mode started. Sign up or login to save changes.',
    keep: 'Keep',
    language: 'Language',
    lastSeen: 'Last seen',
    lastPinged: 'Last pinged',
    lastUpdated: 'Last updated',
    lastVerified: 'Last verified',
    leaveBoard: 'Leave board',
    leaveCurrentBoard: 'Leave current board',
    leaveTaskShare: 'Leave shared task',
    localDesktopModePersistent: 'Running locally. Changes are saved on this device and are not synced to the cloud until you log in and choose what to sync.',
    localDesktopModeShort: 'Local',
    loadingAccount: 'Checking account...',
    loadingBoard: 'Loading board...',
    loadingTasks: 'Loading tasks...',
    login: 'Login',
    loginButton: 'Login',
    logout: 'Logout',
    liveUpdatesDisconnected: 'Live updates disconnected. Refresh still works.',
    manageBoards: 'Manage boards',
    newProjectTag: 'New category',
    newTask: 'New task',
    newTaskPlaceholder: 'Add a task and press Enter...',
    newTaskTitlePlaceholder: 'Task title...',
    newView: 'Save filter',
    newWorkspace: 'New board',
    noCategory: 'No category',
    noCategoriesYet: 'No categories yet',
    noColor: 'No color',
    noFollowUp: 'No follow-up',
    noBoardSelected: 'Create a board first, then add tasks to it.',
    noNotesYet: 'No notes yet',
    noStatus: 'No status',
    noTaskColors: 'No task colors yet',
    noArchivedTasksToDelete: 'No matching archived tasks were found.',
    noTasks: 'Nothing here yet. Use + to add your first task.',
    noTasksMatch: 'No tasks match these filters. Reset filters to see the whole wall again.',
    noIncomingNotifications: 'No pending invitations or shared tasks.',
    noSessions: 'No sessions yet.',
    notSignedIn: 'Not signed in',
    notTouchedDays: 'Not touched days',
    olderThanDays: 'Older than days',
    note: 'Note',
    noteCount: 'notes',
    notes: 'Notes',
    oauthLogin: 'OAuth login',
    oauthLoginHelp: 'Microsoft login appears here when it is enabled by the server.',
    offline: 'Offline',
    online: 'Online',
    overview: 'All tasks',
    password: 'Password',
    passwordRequirement: 'Use at least 8 characters. Longer passphrases are better.',
    projectTags: 'Categories',
    refresh: 'Refresh',
    register: 'Register',
    registerButton: 'Create account',
    removeMember: 'Remove member',
    removeFilters: 'Remove filters',
    requireArchiveNote: 'Require archive note',
    resetFilters: 'Reset filters',
    revoked: 'Revoked',
    revokeSession: 'Revoke',
    roleMember: 'Member',
    roleOwner: 'Owner',
    roleReadOnly: 'Read-only / Guest',
    save: 'Save',
    saveFailed: 'Save failed',
    saveFields: 'Save fields',
    saved: 'Saved',
    savedViews: 'Wall',
    saving: 'Saving...',
    sessionBrowser: 'Browser',
    sessionDesktopCloud: 'Desktop cloud',
    sessionDesktopLocal: 'Local desktop',
    sessionDevelopment: 'Development',
    sessionGuest: 'Guest',
    sessionRevoked: 'Session revoked.',
    sessions: 'Sessions',
    selectTasksForAction: 'Select task(s) for action',
    selectedTasks: 'selected',
    settings: 'Settings',
    settingsGeneral: 'General',
    settingsSections: 'Settings sections',
    signInMethods: 'Sign-in methods',
    signedInAs: 'Signed in as',
    signupClosed: 'Registration is closed on this server. Ask the owner for access.',
    signupInviteOnlyHelp: 'This server is invite-only. Enter your invite code to create an account.',
    signupWhitelistHelp: 'This server only accepts approved emails or domains.',
    sortAscending: 'ascending',
    sortCreated: 'Created',
    sortDescending: 'descending',
    sortFollowUp: 'Follow-up',
    sortLastTouched: 'Last updated',
    sortStatus: 'Status',
    sortTitle: 'Title',
    sortedBy: 'Sorted by',
    stale: 'Stale',
    status: 'Status',
    statusOptions: 'Status options',
    taskColor: 'Task color',
    taskFields: 'Task fields',
    taskTitleRequired: 'Title *',
    templateImported: 'Template imported.',
    templates: 'Task templates',
    undo: 'Undo',
    unarchiveNote: 'Unarchive note (optional)',
    unarchiveSelected: 'Unarchive selected',
    unknownDevice: 'Unknown device',
    updatingTasks: 'Updating...',
    useDevelopmentAccount: 'Use dev account',
    waiting: 'Waiting',
    wallHelp: 'Search tasks by text, category, status, field values, color, and dates.',
    acceptInvite: 'Accept invite',
    inviteEmail: 'Invite email',
    inviteCode: 'Invite code',
    inviteMember: 'Invite member',
    inviteToken: 'Invite token',
    inviteTokenHelp: 'Copy this token to the other user while email delivery is paused.',
    inviteUrl: 'Invite URL',
    importTemplate: 'Import template',
    importTemplateHelp: 'Copy this task structure into your template library.',
    members: 'Members',
    notShared: 'Not shared',
    pendingInvites: 'pending',
    removeShare: 'Remove share',
    revokeInvite: 'Revoke invite',
    shareEmail: 'Share email',
    shareRole: 'Share role',
    shareLinkHelp: 'Copy this one-time link to the invited user. It expires after one day unless revoked first.',
    shareSelected: 'Share selected',
    shareTask: 'Share task',
    sharedWith: 'Shared with',
    sharedWithMe: 'Shared with me',
    sharedBy: 'Shared by',
    sharedWorkspace: 'Shared board',
    boardAccessCannotCreateTasks: 'This board access cannot create new tasks.',
    sharedBoardsCannotCreateTasks: 'This board access cannot create new tasks.',
    sharing: 'Sharing',
    invitedBy: 'Invited by',
    notifications: 'Notifications',
    taskShareLeft: 'Shared task left.',
    tasksCopied: 'Task(s) copied.',
    tasksDeletedPermanently: 'Archived task(s) deleted.',
    tasksUnarchived: 'Task(s) unarchived.',
    workspaceColor: 'Board color',
    workspaceInviteAccepted: 'Invitation accepted.',
    workspaceInviteDeclined: 'Invitation declined.',
    workspaceDeleted: 'Board deleted.',
    systemBoardCannotBeDeleted: 'All tasks is a standard wall and cannot be deleted.',
    cloudAccount: 'Cloud account',
    cloudAccountConnected: 'Cloud account connected.',
    cloudAccountDisconnected: 'Cloud account disconnected.',
    cloudAccountHelp: 'Connect this local desktop to the cloud server configured for this client.',
    cloudAccountRequiredForSync: 'Connect a cloud account in Account before syncing this board.',
    cloudSyncPaused: 'Cloud sync is paused; local work is still safe',
    cloudApiUrl: 'Cloud API URL',
    cloudServerUrl: 'Cloud server URL',
    cloudServerUrlNotConfigured: 'No cloud server URL is configured for this client.',
    cloudSessionToken: 'Cloud session token',
    cloudSync: 'Cloud sync',
    connectCloudAccount: 'Login',
    disconnectCloudAccount: 'Disconnect cloud account',
    pullCloudChanges: 'Pull cloud changes',
    pushLocalChanges: 'Push local changes',
    retrySync: 'Retry sync',
    syncBoard: 'Sync board',
    syncComplete: 'Sync complete',
    syncConflicts: 'Conflicts',
    syncConflict: 'Sync conflict',
    syncDeleted: 'Deleted in sync',
    syncError: 'Sync error',
    syncFailed: 'Sync failed',
    syncFailedCount: 'Failed',
    syncLastAttempt: 'Last sync attempt',
    syncLastSynced: 'Last synced',
    syncMessages: 'Sync messages',
    syncNeedsReview: 'Needs review',
    syncNow: 'Sync now',
    syncPushed: 'Pushed',
    syncPulled: 'Pulled',
    syncRecoveryHelp: 'Conflicts and failed items are kept on both sides. Open the task, decide what should win, then retry sync.',
    syncRootLinked: 'Linked',
    syncRootLocalOnly: 'Local only',
    syncStats: 'Sync stats',
    syncSynced: 'Synced',
    syncing: 'Syncing...',
    syncTokenHelp: 'Paste a browser/cloud session token for this run. DumpTether remembers only the cloud URL, not the token.',
    syncUnknown: 'Sync state unknown',
    syncUpdatedLocal: 'Updated local',
    syncUpdatedRemote: 'Updated cloud',
    workspaceInvites: 'Board invitations',
    workspaceLeft: 'Board left.',
    workspaces: 'Boards',
  },
  da: {
    account: 'Konto',
    activeTask: 'Aktiv opgave',
    addArchiveReason: 'Tilføj arkivårsag',
    addNotePlaceholder: 'Tilføj en note og tryk Enter...',
    addStatus: 'Tilføj status',
    addTask: 'Tilføj opgave',
    allProjects: 'Alle kategorier',
    allWorkspaces: 'Alle tavler',
    anyCategory: 'Alle kategorier',
    anyColor: 'Alle farver',
    anyFollowUp: 'Alle opfølgninger',
    anyProject: 'Alle kategorier',
    anyStatus: 'Alle statusser',
    archive: 'Arkiv',
    archiveActions: 'Arkivhandlinger',
    archiveAction: 'Arkivér',
    archiveCategory: 'Arkivér kategori',
    archiveReasons: 'Arkivårsager',
    archiveSelected: 'Arkivér valgte',
    archiveTasks: 'Arkivér opgave(r)',
    archivedTask: 'Arkiveret opgave',
    authLoggedIn: 'Logget ind.',
    authRegistered: 'Konto oprettet og logget ind.',
    authRequiredBody: 'Log ind eller opret en bruger, før du bruger tavlen.',
    authRequiredTitle: 'Log ind på DumpTether',
    authSettingsHelp: 'Lokale og hostede brugere bruger samme session- og tavleregler.',
    backToWall: 'Tilbage til tavlen',
    backendOffline: 'Backendforbindelsen er ikke tilgængelig',
    backendOnline: 'Backendforbindelsen virker',
    board: 'Tavle',
    boardColor: 'Tavlefarve',
    cancel: 'Annuller',
    category: 'Kategori',
    changeCategory: 'Skift kategori',
    changeColor: 'Skift farve',
    changeDueDate: 'Skift dato',
    changeStatus: 'Skift status',
    clearArchive: 'Ryd arkiv',
    clearColor: 'Ryd farve',
    clearOldTasks: 'Ryd gamle opgaver...',
    clearWorkspaceTasks: 'Ryd opgaver i tavle...',
    cleanup: 'Oprydning',
    cleanupFuture: 'Permanent oprydning er begrænset til den valgte tavle og kræver altid bekræftelse.',
    cleanupArchiveWarning: 'Dette sletter matchende arkiverede opgaver permanent, inklusive noter og historik. Det kan ikke fortrydes.',
    cleanupCloudLinkedUnavailable: 'Permanent oprydning er sat på pause for cloud-forbundne tavler, indtil sletninger kan synkroniseres sikkert.',
    cleanupBoard: 'Tavle der skal ryddes op',
    cleanupNeedsOwnedBoard: 'Opret eller vælg en tavle, du ejer, før permanent oprydning kan bruges.',
    close: 'Luk',
    collapseSidebar: 'Skjul sidebar',
    color: 'Farve',
    configRequired: 'Kræver opsætning',
    confirmDelete: 'Sikker?',
    connectionLostToast: 'Forbindelsen til serveren er væk. Du kan se cachede opgaver, men ændringer kan fejle indtil den er tilbage.',
    continueWith: 'Fortsæt med',
    continueWithoutAccount: 'Fortsæt uden konto',
    continueWithoutAccountHelp: 'Demo-adgang gemmer ikke aendringer paa serveren. Opret konto eller log ind for at gemme.',
    copiedToClipboard: 'Kopieret til udklipsholder!',
    copySelected: 'Kopier valgte',
    copyToBoard: 'Kopier til tavle',
    createBoardBeforeTasks: 'Opret eller vælg en tavle, før du opretter opgaver.',
    created: 'Oprettet',
    currentSession: 'aktuel',
    danish: 'Dansk',
    declineInvite: 'Afvis',
    deleteBoard: 'Slet tavle...',
    deleteBoardConfirmBody: 'Dette sletter tavlen, opgaver, arkiv og historik permanent. Handlingen kan ikke fortrydes.',
    deleteBoardFuture: 'Slet tavle er planlagt og kræver en rigtig ryddepolitik først.',
    deleteBoardNow: 'Slet tavle',
    deleteArchivedNow: 'Slet arkiverede opgaver',
    deleteArchivedTasksWarning: 'Dette sletter de valgte arkiverede opgaver permanent, inklusive noter, felter, delinger og historik. Handlingen kan ikke fortrydes.',
    deleteCategoryNow: 'Slet kategori',
    deleteCategoryWarning: 'Slet denne kategori og lad opgaverne stå uden kategori?',
    deleteNote: 'Slet note',
    deletePermanently: 'Slet permanent',
    deleteProjectTag: 'Slet kategori...',
    developmentAccountHelp: 'Kun udvikling: opretter eller logger ind som lokal dev-bruger.',
    deviceName: 'Enhedsnavn',
    displayName: 'Visningsnavn',
    done: 'Stop valg',
    draftTaskHelp: 'Denne kladde er ikke gemt endnu. Skriv en titel og opret den, så kan du tilføje noter og felter bagefter.',
    editBoard: 'Rediger tavle',
    editMode: 'Rediger',
    editProject: 'Rediger kategori',
    editTask: 'Rediger opgave',
    editView: 'Rediger filter',
    email: 'Email',
    emailConfirmationSent: 'Bekræftelsesmail sendt. Åbn den før login.',
    emailMfa: 'Email-MFA',
    emailMfaHelp: 'Fremtidige mistænkelige logins sender en kort kode på email.',
    emailPasswordLogin: 'Email og adgangskode',
    emailPasswordLoginHelp: 'Kan bruges nu. Emailbekræftelse er næste sikkerhedstrin.',
    english: 'Engelsk',
    expires: 'Udløber',
    expandSidebar: 'Vis sidebar',
    fieldsForFiltering: 'Felter',
    fieldsHelp: 'Strukturerede felter gør det muligt at filtrere uden at gøre tavlen til en stor formular.',
    filterWall: 'Filtrer tavlen...',
    followUp: 'Opfølgning',
    followUpDate: 'Opfølgning',
    guestModePersistent: 'Demo-tilstand: opret konto eller log ind for at gemme aendringer.',
    guestModeShort: 'Midlertidig',
    guestModeToast: 'Demo-tilstand startet. Opret konto eller log ind for at gemme.',
    keep: 'Behold',
    language: 'Sprog',
    lastSeen: 'Sidst set',
    lastPinged: 'Sidst pinget',
    lastUpdated: 'Sidst opdateret',
    lastVerified: 'Sidst bekræftet',
    leaveBoard: 'Forlad tavle',
    leaveCurrentBoard: 'Forlad aktuel tavle',
    leaveTaskShare: 'Forlad delt opgave',
    localDesktopModePersistent: 'Kører lokalt. Ændringer gemmes på denne enhed og synkroniseres ikke til cloud, før du logger ind og vælger hvad der skal synkroniseres.',
    localDesktopModeShort: 'Lokal',
    loadingAccount: 'Tjekker konto...',
    loadingBoard: 'Indlæser tavle...',
    loadingTasks: 'Indlæser opgaver...',
    login: 'Log ind',
    loginButton: 'Log ind',
    logout: 'Log ud',
    liveUpdatesDisconnected: 'Live opdateringer er afbrudt. Opdater virker stadig.',
    manageBoards: 'Administrer tavler',
    newProjectTag: 'Ny kategori',
    newTask: 'Ny opgave',
    newTaskPlaceholder: 'Tilføj en opgave og tryk Enter...',
    newTaskTitlePlaceholder: 'Opgavetitel...',
    newView: 'Gem filter',
    newWorkspace: 'Ny tavle',
    noCategory: 'Ingen kategori',
    noCategoriesYet: 'Ingen kategorier endnu',
    noColor: 'Ingen farve',
    noFollowUp: 'Ingen opfølgning',
    noBoardSelected: 'Opret en tavle først, og tilføj derefter opgaver.',
    noNotesYet: 'Ingen noter endnu',
    noStatus: 'Ingen status',
    noTaskColors: 'Ingen opgavefarver endnu',
    noArchivedTasksToDelete: 'Der blev ikke fundet matchende arkiverede opgaver.',
    noTasks: 'Her er tomt endnu. Brug + for at tilføje din første opgave.',
    noTasksMatch: 'Ingen opgaver matcher filtrene. Nulstil filtrene for at se hele tavlen igen.',
    noIncomingNotifications: 'Ingen ventende invitationer eller delte opgaver.',
    noSessions: 'Ingen sessioner endnu.',
    notSignedIn: 'Ikke logget ind',
    notTouchedDays: 'Ikke rørt i dage',
    olderThanDays: 'Ældre end antal dage',
    note: 'Note',
    noteCount: 'noter',
    notes: 'Noter',
    oauthLogin: 'OAuth-login',
    oauthLoginHelp: 'Microsoft-login vises her, når det er slået til på serveren.',
    offline: 'Offline',
    online: 'Online',
    overview: 'Alle opgaver',
    password: 'Adgangskode',
    passwordRequirement: 'Brug mindst 8 tegn. En længere adgangssætning er bedre.',
    projectTags: 'Kategorier',
    refresh: 'Opdater',
    register: 'Opret konto',
    registerButton: 'Opret konto',
    removeMember: 'Fjern medlem',
    removeFilters: 'Fjern filtre',
    requireArchiveNote: 'Kræv arkivnote',
    resetFilters: 'Nulstil filtre',
    revoked: 'Tilbagekaldt',
    revokeSession: 'Tilbagekald',
    roleMember: 'Medlem',
    roleOwner: 'Ejer',
    roleReadOnly: 'Læseadgang / gæst',
    save: 'Gem',
    saveFailed: 'Kunne ikke gemme',
    saveFields: 'Gem felter',
    saved: 'Gemt',
    savedViews: 'Tavle',
    saving: 'Gemmer...',
    sessionBrowser: 'Browser',
    sessionDesktopCloud: 'Desktop cloud',
    sessionDesktopLocal: 'Lokal desktop',
    sessionDevelopment: 'Udvikling',
    sessionGuest: 'Gæst',
    sessionRevoked: 'Session tilbagekaldt.',
    sessions: 'Sessioner',
    selectTasksForAction: 'Vælg opgave(r) til handling',
    selectedTasks: 'valgt',
    settings: 'Indstillinger',
    settingsGeneral: 'Generelt',
    settingsSections: 'Indstillingsområder',
    signInMethods: 'Loginmetoder',
    signedInAs: 'Logget ind som',
    signupClosed: 'Oprettelse er lukket paa denne server. Spoerg ejeren om adgang.',
    signupInviteOnlyHelp: 'Denne server kraever invitation. Indtast din invitationskode for at oprette konto.',
    signupWhitelistHelp: 'Denne server tillader kun godkendte emails eller domainer.',
    sortAscending: 'stigende',
    sortCreated: 'Oprettet',
    sortDescending: 'faldende',
    sortFollowUp: 'Opfølgning',
    sortLastTouched: 'Sidst opdateret',
    sortStatus: 'Status',
    sortTitle: 'Titel',
    sortedBy: 'Sorteret efter',
    stale: 'Gammel',
    status: 'Status',
    statusOptions: 'Statusmuligheder',
    taskColor: 'Opgavefarve',
    taskFields: 'Opgavefelter',
    taskTitleRequired: 'Titel *',
    templateImported: 'Skabelon importeret.',
    templates: 'Opgaveskabeloner',
    undo: 'Fortryd',
    unarchiveNote: 'Genåbningsnote (valgfri)',
    unarchiveSelected: 'Genåbn valgte',
    updatingTasks: 'Opdaterer...',
    unknownDevice: 'Ukendt enhed',
    useDevelopmentAccount: 'Brug dev-konto',
    waiting: 'Afventer',
    wallHelp: 'Søg i opgaver efter tekst, kategori, status, feltværdier, farve og datoer.',
    acceptInvite: 'Accepter invitation',
    inviteEmail: 'Inviter email',
    inviteCode: 'Invitationskode',
    inviteMember: 'Inviter medlem',
    inviteToken: 'Invitationstoken',
    inviteTokenHelp: 'Kopier denne token til den anden bruger mens email er sat paa pause.',
    inviteUrl: 'Invitationslink',
    importTemplate: 'Importer skabelon',
    importTemplateHelp: 'Kopier denne opgaves struktur til dine skabeloner.',
    members: 'Medlemmer',
    notShared: 'Ikke delt',
    pendingInvites: 'afventer',
    removeShare: 'Fjern deling',
    revokeInvite: 'Tilbagekald invitation',
    shareEmail: 'Delings-email',
    shareRole: 'Delingsrolle',
    shareLinkHelp: 'Kopier dette engangslink til den inviterede bruger. Det udløber efter én dag, medmindre det tilbagekaldes først.',
    shareSelected: 'Del valgte',
    shareTask: 'Del opgave',
    sharedWith: 'Delt med',
    sharedWithMe: 'Delt med mig',
    sharedBy: 'Delt af',
    sharedWorkspace: 'Delt tavle',
    boardAccessCannotCreateTasks: 'Denne tavleadgang kan ikke oprette nye opgaver.',
    sharedBoardsCannotCreateTasks: 'Denne tavleadgang kan ikke oprette nye opgaver.',
    sharing: 'Deling',
    invitedBy: 'Inviteret af',
    notifications: 'Notifikationer',
    taskShareLeft: 'Delt opgave forladt.',
    tasksCopied: 'Opgave(r) kopieret.',
    tasksDeletedPermanently: 'Arkiverede opgave(r) slettet.',
    tasksUnarchived: 'Opgave(r) genåbnet.',
    workspaceColor: 'Tavlefarve',
    workspaceInviteAccepted: 'Invitation accepteret.',
    workspaceInviteDeclined: 'Invitation afvist.',
    workspaceDeleted: 'Tavlen blev slettet.',
    systemBoardCannotBeDeleted: 'Alle opgaver er en standardtavle og kan ikke slettes.',
    cloudAccount: 'Cloud-konto',
    cloudAccountConnected: 'Cloud-konto forbundet.',
    cloudAccountDisconnected: 'Cloud-konto afbrudt.',
    cloudAccountHelp: 'Forbind denne lokale desktop til cloud-serveren, der er konfigureret for denne klient.',
    cloudAccountRequiredForSync: 'Forbind en cloud-konto under Konto, før du synker denne tavle.',
    cloudSyncPaused: 'Cloud-synkronisering er sat på pause; lokalt arbejde er stadig sikkert',
    cloudApiUrl: 'Cloud API-URL',
    cloudServerUrl: 'Cloud-server URL',
    cloudServerUrlNotConfigured: 'Der er ikke konfigureret en cloud-server URL for denne klient.',
    cloudSessionToken: 'Cloud-sessiontoken',
    cloudSync: 'Cloud-synk',
    connectCloudAccount: 'Log ind',
    disconnectCloudAccount: 'Afbryd cloud-konto',
    pullCloudChanges: 'Hent cloud-ændringer',
    pushLocalChanges: 'Send lokale ændringer',
    retrySync: 'Prøv synk igen',
    syncBoard: 'Synk tavle',
    syncComplete: 'Synk færdig',
    syncConflicts: 'Konflikter',
    syncConflict: 'Synkkonflikt',
    syncDeleted: 'Slettet i synk',
    syncError: 'Synkfejl',
    syncFailed: 'Synk fejlede',
    syncFailedCount: 'Fejlede',
    syncLastAttempt: 'Sidste synkforsøg',
    syncLastSynced: 'Sidst synket',
    syncMessages: 'Synkbeskeder',
    syncNeedsReview: 'Kræver gennemgang',
    syncNow: 'Synk nu',
    syncPushed: 'Sendt',
    syncPulled: 'Hentet',
    syncRecoveryHelp: 'Konflikter og fejlede elementer beholdes på begge sider. Åbn opgaven, vælg hvad der skal gælde, og prøv synk igen.',
    syncRootLinked: 'Forbundet',
    syncRootLocalOnly: 'Kun lokalt',
    syncStats: 'Synkstatus',
    syncSynced: 'Synket',
    syncing: 'Synker...',
    syncTokenHelp: 'Indsæt et browser/cloud-sessiontoken for denne kørsel. DumpTether husker kun cloud-URLen, ikke tokenet.',
    syncUnknown: 'Ukendt synkstatus',
    syncUpdatedLocal: 'Opdateret lokalt',
    syncUpdatedRemote: 'Opdateret i cloud',
    workspaceInvites: 'Tavleinvitationer',
    workspaceLeft: 'Tavle forladt.',
    workspaces: 'Tavler',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;
export type Translate = (key: TranslationKey) => string;

export function translate(language: Language, key: TranslationKey) {
  return translations[language][key] ?? translations.en[key];
}
