// <auto-generated />
using System;
using DumpTether.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DumpTether.Data.Sqlite.Migrations
{
    [DbContext(typeof(DumpTetherDbContext))]
    partial class DumpTetherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DumpTether.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailConfirmedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("email_confirmed_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.ArchiveResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresExplanation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requires_explanation");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("archive_resolutions", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.CloudSyncAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CloudApiBaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("cloud_api_base_url");

                    b.Property<string>("CloudDisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("cloud_display_name");

                    b.Property<string>("CloudEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("cloud_email");

                    b.Property<Guid>("CloudUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cloud_user_id");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("connected_at");

                    b.Property<DateTimeOffset?>("DisconnectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("disconnected_at");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_verified_at");

                    b.Property<string>("ProtectedSessionToken")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("protected_session_token");

                    b.Property<DateTimeOffset>("SessionExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_expires_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("cloud_sync_accounts", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.EmailConfirmationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt", "UsedAt");

                    b.ToTable("email_confirmation_tokens", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailAtLogin")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email_at_login");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("external_logins", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.FieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<int>("LayoutColumn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("layout_column");

                    b.Property<int>("LayoutColumnSpan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("layout_column_span");

                    b.Property<int>("LayoutRow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("layout_row");

                    b.Property<int>("LayoutRowSpan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("layout_row_span");

                    b.Property<double>("LayoutWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.0)
                        .HasColumnName("layout_weight");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("options");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Header")
                        .HasColumnName("scope");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TaskTemplateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_template_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("TaskTemplateId", "Scope", "Key");

                    b.HasIndex("TaskTemplateId", "Scope", "SortOrder");

                    b.ToTable("field_definitions", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.FieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("field_definition_id");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_item_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("TaskItemId", "FieldDefinitionId")
                        .IsUnique();

                    b.ToTable("field_values", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name", "IsActive")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.SavedView", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("definition");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<string>("SortJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sort");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasFilter("project_id IS NULL AND deleted_at IS NULL");

                    b.HasIndex("WorkspaceId", "ProjectId", "Name")
                        .IsUnique()
                        .HasFilter("project_id IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("saved_views", null, t =>
                        {
                            t.HasCheckConstraint("ck_saved_views_scope_project", "(scope = 'Workspace' AND project_id IS NULL) OR (scope = 'Project' AND project_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DumpTether.Domain.SyncMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset?>("LastAttemptedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_attempted_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<string>("LastRemoteVersion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_remote_version");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_synced_at");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("local_id");

                    b.Property<Guid?>("RemoteId")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncRootId")
                        .HasColumnType("TEXT")
                        .HasColumnName("sync_root_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SyncRootId", "EntityType", "LocalId")
                        .IsUnique();

                    b.HasIndex("SyncRootId", "EntityType", "RemoteId")
                        .IsUnique()
                        .HasFilter("remote_id IS NOT NULL");

                    b.ToTable("sync_mappings", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.SyncRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("CloudUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cloud_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_synced_at");

                    b.Property<Guid>("LocalWorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("local_workspace_id");

                    b.Property<Guid?>("RemoteWorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_workspace_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LocalWorkspaceId")
                        .IsUnique();

                    b.HasIndex("CloudUserId", "RemoteWorkspaceId")
                        .IsUnique()
                        .HasFilter("cloud_user_id IS NOT NULL AND remote_workspace_id IS NOT NULL");

                    b.ToTable("sync_roots", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArchiveResolutionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("archive_resolution_id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<string>("Category")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FollowUpAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("follow_up_at");

                    b.Property<DateTimeOffset>("LastTouchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_touched_at");

                    b.Property<DateTimeOffset?>("LastViewedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_viewed_at");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaskTemplateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveResolutionId");

                    b.HasIndex("FollowUpAt");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskTemplateId");

                    b.HasIndex("WorkspaceId", "Category");

                    b.HasIndex("WorkspaceId", "Color");

                    b.HasIndex("WorkspaceId", "ArchivedAt", "LastTouchedAt");

                    b.HasIndex("WorkspaceId", "ProjectId", "ArchivedAt");

                    b.ToTable("task_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_items_archive_requires_resolution", "(archived_at IS NULL AND archive_resolution_id IS NULL) OR (archived_at IS NOT NULL AND archive_resolution_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DumpTether.Domain.TaskItemShare", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_email");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<Guid>("SharedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("shared_by_user_id");

                    b.Property<Guid?>("SharedWithUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("shared_with_user_id");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_item_id");

                    b.Property<string>("TokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("SharedByUserId");

                    b.HasIndex("SharedWithUserId");

                    b.HasIndex("TokenHash");

                    b.HasIndex("TaskItemId", "NormalizedEmail", "RevokedAt");

                    b.HasIndex("WorkspaceId", "NormalizedEmail", "RevokedAt");

                    b.ToTable("task_item_shares", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EntryLayoutJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]")
                        .HasColumnName("entry_layout_json");

                    b.Property<string>("HeaderLayoutJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]")
                        .HasColumnName("header_layout_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Name");

                    b.ToTable("task_templates", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.TaskTimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_item_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId", "OccurredAt");

                    b.ToTable("task_timeline_entries", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.TaskTimelineEntryFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("field_definition_id");

                    b.Property<Guid>("TaskTimelineEntryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_timeline_entry_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("TaskTimelineEntryId", "FieldDefinitionId")
                        .IsUnique();

                    b.ToTable("task_timeline_entry_field_values", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_name");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddressHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address_hash");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_token_hash");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_type");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt", "RevokedAt");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.WorkspaceInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_email");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "NormalizedEmail", "AcceptedAt", "RevokedAt");

                    b.ToTable("workspace_invitations", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.WorkspaceMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("workspace_memberships", (string)null);
                });

            modelBuilder.Entity("DumpTether.Domain.ArchiveResolution", b =>
                {
                    b.HasOne("DumpTether.Domain.Workspace", null)
                        .WithMany("_archiveResolutions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.CloudSyncAccount", b =>
                {
                    b.HasOne("DumpTether.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.EmailConfirmationToken", b =>
                {
                    b.HasOne("DumpTether.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.ExternalLogin", b =>
                {
                    b.HasOne("DumpTether.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.FieldDefinition", b =>
                {
                    b.HasOne("DumpTether.Domain.TaskTemplate", null)
                        .WithMany("_fieldDefinitions")
                        .HasForeignKey("TaskTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.FieldValue", b =>
                {
                    b.HasOne("DumpTether.Domain.FieldDefinition", null)
                        .WithMany()
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DumpTether.Domain.TaskItem", null)
                        .WithMany("_fieldValues")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.Project", b =>
                {
                    b.HasOne("DumpTether.Domain.Workspace", null)
                        .WithMany("_projects")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.SavedView", b =>
                {
                    b.HasOne("DumpTether.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DumpTether.Domain.Workspace", null)
                        .WithMany("_savedViews")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.SyncMapping", b =>
                {
                    b.HasOne("DumpTether.Domain.SyncRoot", null)
                        .WithMany()
                        .HasForeignKey("SyncRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.SyncRoot", b =>
                {
                    b.HasOne("DumpTether.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("LocalWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.TaskItem", b =>
                {
                    b.HasOne("DumpTether.Domain.ArchiveResolution", null)
                        .WithMany()
                        .HasForeignKey("ArchiveResolutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DumpTether.Domain.Project", null)
                        .WithMany("_taskItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DumpTether.Domain.TaskTemplate", null)
                        .WithMany()
                        .HasForeignKey("TaskTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DumpTether.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.TaskItemShare", b =>
                {
                    b.HasOne("DumpTether.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("SharedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DumpTether.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("SharedWithUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DumpTether.Domain.TaskItem", null)
                        .WithMany("Shares")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DumpTether.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.TaskTemplate", b =>
                {
                    b.HasOne("DumpTether.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DumpTether.Domain.TaskTimelineEntry", b =>
                {
                    b.HasOne("DumpTether.Domain.TaskItem", null)
                        .WithMany("_timelineEntries")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.TaskTimelineEntryFieldValue", b =>
                {
                    b.HasOne("DumpTether.Domain.FieldDefinition", null)
                        .WithMany()
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DumpTether.Domain.TaskTimelineEntry", null)
                        .WithMany("FieldValues")
                        .HasForeignKey("TaskTimelineEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.UserSession", b =>
                {
                    b.HasOne("DumpTether.Domain.AppUser", null)
                        .WithMany("_sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.WorkspaceInvitation", b =>
                {
                    b.HasOne("DumpTether.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DumpTether.Domain.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.WorkspaceMembership", b =>
                {
                    b.HasOne("DumpTether.Domain.AppUser", null)
                        .WithMany("_workspaceMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DumpTether.Domain.Workspace", null)
                        .WithMany("_memberships")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DumpTether.Domain.AppUser", b =>
                {
                    b.Navigation("_sessions");

                    b.Navigation("_workspaceMemberships");
                });

            modelBuilder.Entity("DumpTether.Domain.Project", b =>
                {
                    b.Navigation("_taskItems");
                });

            modelBuilder.Entity("DumpTether.Domain.TaskItem", b =>
                {
                    b.Navigation("Shares");

                    b.Navigation("_fieldValues");

                    b.Navigation("_timelineEntries");
                });

            modelBuilder.Entity("DumpTether.Domain.TaskTemplate", b =>
                {
                    b.Navigation("_fieldDefinitions");
                });

            modelBuilder.Entity("DumpTether.Domain.TaskTimelineEntry", b =>
                {
                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("DumpTether.Domain.Workspace", b =>
                {
                    b.Navigation("_archiveResolutions");

                    b.Navigation("_memberships");

                    b.Navigation("_projects");

                    b.Navigation("_savedViews");
                });
#pragma warning restore 612, 618
        }
    }
}
